package com.example.colculationart;


import java.util.HashMap;
import java.util.Map;

public class  HMap {
    public static HashMap<Integer, String> getUiMap(){
        HashMap<Integer, String> UiBelongCharacterName = new HashMap<>();
        UiBelongCharacterName.put(1, "1_Alhaitham");
        UiBelongCharacterName.put(2, "2_Albedo");
        UiBelongCharacterName.put(3,"3_KamisatoAyaka");
        UiBelongCharacterName.put(4,"4_KamisatoAyato");
        UiBelongCharacterName.put(5,"5_Venti");
        UiBelongCharacterName.put(6,"6_Ganyu");
        UiBelongCharacterName.put(7,"7_Jean");
        UiBelongCharacterName.put(8,"8_Diluc");
        UiBelongCharacterName.put(9, "9_Dehya");
        UiBelongCharacterName.put(10,"10_Yelan");
        UiBelongCharacterName.put(11,"11_Yoimiya");
        UiBelongCharacterName.put(12,"12_AratakiItto");
        UiBelongCharacterName.put(13,"13_KaedeharaKazuha");
        UiBelongCharacterName.put(14,"14_Klee");
        UiBelongCharacterName.put(15,"15_SangonomiyaKokomi");
        UiBelongCharacterName.put(16,"16_Keqing");
        UiBelongCharacterName.put(17,"17_Traveler");
        UiBelongCharacterName.put(18,"17_Traveler");
        UiBelongCharacterName.put(19,"17_Traveler");
        UiBelongCharacterName.put(20,"17_Traveler");
        UiBelongCharacterName.put(21,"21_Mona");
        UiBelongCharacterName.put(22,"22_Nahida");
        UiBelongCharacterName.put(23,"23_Nilou");
        UiBelongCharacterName.put(24,"24_RaidenShogun");
        UiBelongCharacterName.put(25,"25_Cyno");
        UiBelongCharacterName.put(26,"26_Wanderer");
        UiBelongCharacterName.put(27,"27_Xiao");
        UiBelongCharacterName.put(28,"28_Tartaglia");
        UiBelongCharacterName.put(29,"29_Tighnari");
        UiBelongCharacterName.put(30,"30_HuTao");
        UiBelongCharacterName.put(31,"31_Qiqi");
        UiBelongCharacterName.put(32,"32_Zhongli");
        UiBelongCharacterName.put(33,"33_Shenhe");
        UiBelongCharacterName.put(34,"34_Aloy");
        UiBelongCharacterName.put(35,"35_Eula");
        UiBelongCharacterName.put(36,"36_YaeMiko");
        UiBelongCharacterName.put(37,"37_Barbara");
        UiBelongCharacterName.put(38,"38_Bennett");
        UiBelongCharacterName.put(39,"39_Beidou");
        UiBelongCharacterName.put(40,"40_Gorou");
        UiBelongCharacterName.put(41,"41_Diona");
        UiBelongCharacterName.put(42,"42_Dori");
        UiBelongCharacterName.put(43,"43_Candace");
        UiBelongCharacterName.put(44,"44_Collei");
        UiBelongCharacterName.put(45,"45_Kaeya");
        UiBelongCharacterName.put(46,"46_Layla");
        UiBelongCharacterName.put(47,"47_Lisa");
        UiBelongCharacterName.put(48,"48_Mika");
        UiBelongCharacterName.put(49,"49_Ningguang");
        UiBelongCharacterName.put(50,"50_Noelle");
        UiBelongCharacterName.put(51,"51_Rosaria");
        UiBelongCharacterName.put(52,"52_Razor");
        UiBelongCharacterName.put(53,"53_KujouSara");
        UiBelongCharacterName.put(54,"54_Sucrose");
        UiBelongCharacterName.put(55,"55_Sayu");
        UiBelongCharacterName.put(56,"56_Xingqiu");
        UiBelongCharacterName.put(57,"57_KukiShinobu");
        UiBelongCharacterName.put(58,"58_Xinyan");
        UiBelongCharacterName.put(59,"59_Xiangling");
        UiBelongCharacterName.put(60,"60_Thoma");
        UiBelongCharacterName.put(61,"61_Faruzan");
        UiBelongCharacterName.put(62,"62_Fischl");
        UiBelongCharacterName.put(63,"63_ShikanoinHeizou");
        UiBelongCharacterName.put(64,"64_Chongyun");
        UiBelongCharacterName.put(65,"65_Amber");
        UiBelongCharacterName.put(66,"66_YunJin");
        UiBelongCharacterName.put(67,"67_Yanfei");
        UiBelongCharacterName.put(68,"68_Yaoyao");
    return UiBelongCharacterName;
    }
    public static HashMap<String, String> getArtNameMap(){
        HashMap<String, String> UiBelongArtName = new HashMap<>();
        UiBelongArtName.put("Adventurer", "adventurer");
        UiBelongArtName.put("Archaic_petra", "archaic_petra");
        UiBelongArtName.put("Berserker","berserker");
        UiBelongArtName.put("Blizzard Strayer","blizzard_strayer");
        UiBelongArtName.put("Bloodstained Chivalry","bloodstained_chivalry");
        UiBelongArtName.put("Brave Heart","brave_heart");
        UiBelongArtName.put("Crimson Witch of flames","crimson_witch_of_flames");
        UiBelongArtName.put("Deepwood Memories","deepwood_memories");
        UiBelongArtName.put("Defenders Will", "defenders_will");
        UiBelongArtName.put("Echoes of an Offering","echoes_of_an_offering");
        UiBelongArtName.put("Desert Pavilion Chronicle","desert_pavilion_chronicle");
        UiBelongArtName.put("Emblem of Severed Fate","emblem_of_severed_fate");
        UiBelongArtName.put("Flower of Paradise Lost","flower_of_paradise_lost");
        UiBelongArtName.put("Gilded Dreams","gilded_dreams");
        UiBelongArtName.put("Gambler","gambler");
        UiBelongArtName.put("Gladiators Finale","gladiators_finale");
        UiBelongArtName.put("Thundering Fury","thundering_fury");
        UiBelongArtName.put("Heart of Depth","heart_of_depth");
        UiBelongArtName.put("Husk of Opulent Dreams","husk_of_opulent_dreams");
        UiBelongArtName.put("Lavawalker","lavawalker");
        UiBelongArtName.put("Wanderers Troupe","wanderers_troupe");
        UiBelongArtName.put("Tenacity of the Millelith","tenacity_of_the_millelith");
        UiBelongArtName.put("Instructor","instructor");
        UiBelongArtName.put("Lucky Dog","lucky_dog");
        UiBelongArtName.put("Maiden Beloved","maiden_beloved");
        UiBelongArtName.put("Martial Artist","martial_artist");
        UiBelongArtName.put("Noblesse Oblige","noblesse_oblige");
        UiBelongArtName.put("Oceanhued Clam","oceanhued_clam");
        UiBelongArtName.put("Pale Flame","pale_flame");
        UiBelongArtName.put("Thundersoother","thundersoother");
        UiBelongArtName.put("Viridescent Venerer","viridescent_venerer");
        UiBelongArtName.put("Tiny Miracle","tiny_miracle");
        UiBelongArtName.put("Vermillion Hereafter","vermillion_hereafter");
        UiBelongArtName.put("Retracing Bolide","retracing_bolide");
        UiBelongArtName.put("Shimenawa's Reminiscence", "shimenawas_reminiscence");
        UiBelongArtName.put("The Exile", "the_exile");
        UiBelongArtName.put("Resolution of Sojourner", "resolution_of_sojourner");
        UiBelongArtName.put("Marechaussee Hunter", "marechaussee_hunter");
        UiBelongArtName.put("Golden Troupe", "golden_troupe");

        return UiBelongArtName;
    }
    public static HashMap<Integer, String> GetArtStatMap(){
        HashMap<Integer, String> ArtStatName = new HashMap<>();
        ArtStatName.put(1, "HP");
        ArtStatName.put(2, "HP%");
        ArtStatName.put(3,"АТК");
        ArtStatName.put(4,"АТК%");
        ArtStatName.put(5,"ДЕФ");
        ArtStatName.put(6,"ДЕФ%");
        ArtStatName.put(7,"МС");
        ArtStatName.put(8,"ВЭ%");
        ArtStatName.put(9, "КШ%");
        ArtStatName.put(10,"КУ%");
        ArtStatName.put(11,"Бонус ФИЗ");
        ArtStatName.put(12,"Бонус Анемо");
        ArtStatName.put(13,"Бонус Гидро");
        ArtStatName.put(14,"Бонус Гео");
        ArtStatName.put(15,"Бонус Дендро");
        ArtStatName.put(16,"Бонус Киро");
        ArtStatName.put(17,"Бонус Пиро");
        ArtStatName.put(18,"Бонус Электро");
        ArtStatName.put(19,"Healing Bonus");
        ArtStatName.put(20,"КШ% + КУ%");
        ArtStatName.put(21,"АТК% или МС");
        ArtStatName.put(22,"МС или КУ% и КШ%");
        ArtStatName.put(23,"Healing Bonus или HP%");
        ArtStatName.put(24,"АТК% или ВЭ");
        ArtStatName.put(25,"МС или ВЭ");
        ArtStatName.put(26,"HP% или ВЭ");
        ArtStatName.put(27,"Healing Bonus или АТК%");
        ArtStatName.put(28,"ДЕФ% или ВЭ");
        ArtStatName.put(29,"Бонус ФИЗ или АТК%");
        ArtStatName.put(31,"МС или Бонус Анемо");
        ArtStatName.put(32,"МС или Бонус Анемо");
        ArtStatName.put(33,"АТК или Бонус Электро");
        ArtStatName.put(34,"HP% или Бонус Киро");
        ArtStatName.put(35,"Healing Bonus или ДЕФ%");
        ArtStatName.put(36,"МС или КШ%");
        ArtStatName.put(41 ,"ВЭ или АТК% или МС");
        ArtStatName.put(42 ,"HP% или КУ% или КШ%");
        ArtStatName.put(43 ,"АТК% или ДЕФ%");
        ArtStatName.put(44 ,"КШ% или Healing Bonus");
        return ArtStatName;
    }

    public static HashMap<String, String> getCharactersID(){
        HashMap<String, String> characterIDs = new HashMap<>();
        characterIDs.put("312182", "Albedo");
        characterIDs.put("383712", "Alhaitham");
        characterIDs.put("337957", "Aloy");
        characterIDs.put("297535", "Amber");
        characterIDs.put("345514", "Ayato");
        characterIDs.put("314348", "Baizhu");
        characterIDs.put("297517", "Barbara");
        characterIDs.put("297528", "Beidou");
        characterIDs.put("297522", "Bennett");
        characterIDs.put("386384", "Candace");
        characterIDs.put("297532", "Chongyun");
        characterIDs.put("382079", "Collei");
        characterIDs.put("315233", "Cyno");
        characterIDs.put("383716", "Dehya");
        characterIDs.put("297518", "Diluc");
        characterIDs.put("305872", "Diona");
        characterIDs.put("380569", "Dori");
        characterIDs.put("328764", "Eula");
        characterIDs.put("391897", "Faruzan");
        characterIDs.put("297524", "Fischl");
        characterIDs.put("417207", "Freminet");
        characterIDs.put("312173", "Ganyu");
        characterIDs.put("336726", "Gorou");
        characterIDs.put("345516", "Heizou");
        characterIDs.put("314347", "Hu Tao");
        characterIDs.put("345461", "Itto");
        characterIDs.put("297536", "Jean");
        characterIDs.put("297516", "Kaeya");
        characterIDs.put("386489", "Kaveh");
        characterIDs.put("332826", "Kazuha");
        characterIDs.put("297534", "Keqing");
        characterIDs.put("409556", "Kirara");
        characterIDs.put("297521", "Klee");
        characterIDs.put("337140", "Kokomi");
        characterIDs.put("386486", "Layla");
        characterIDs.put("297515", "Lisa");
        characterIDs.put("345879", "Lynette");
        characterIDs.put("345540", "Lyney");
        characterIDs.put("390096", "Mika");
        characterIDs.put("297526", "Mona");
        characterIDs.put("383713", "Nahida");
        characterIDs.put("383715", "Nilou");
        characterIDs.put("297529", "Ningguang");
        characterIDs.put("297523", "Noelle");
        characterIDs.put("297533", "Qiqi");
        characterIDs.put("337161", "Raiden");
        characterIDs.put("297519", "Razor");
        characterIDs.put("314177", "Rosaria");
        characterIDs.put("336727", "Sara");
        characterIDs.put("333496", "Sayu");
        characterIDs.put("346620", "Shenhe");
        characterIDs.put("346199", "Shinobu");
        characterIDs.put("297525", "Sucrose");
        characterIDs.put("305862", "Tartaglia");
        characterIDs.put("337141", "Thoma");
        characterIDs.put("382082", "Tighnari");
        characterIDs.put("297537", "Traveler (Anemo)");
        characterIDs.put("381807", "Traveler (Dendro)");
        characterIDs.put("336865", "Traveler (Electro)");
        characterIDs.put("297538", "Traveler (Geo)");
        characterIDs.put("416602", "Traveler (Hydro)");
        characterIDs.put("297520", "Venti");
        characterIDs.put("309656", "Wanderer");
        characterIDs.put("297530", "Xiangling");
        characterIDs.put("297527", "Xiao");
        characterIDs.put("297531", "Xingqiu");
        characterIDs.put("305873", "Xinyan");
        characterIDs.put("327533", "Yae Miko");
        characterIDs.put("328765", "Yanfei");
        characterIDs.put("314174", "Yaoyao");
        characterIDs.put("372781", "Yelan");
        characterIDs.put("333497", "Yoimiya");
        characterIDs.put("314345", "Yun Jin");
        characterIDs.put("305858", "Zhongli");
        characterIDs.put("Wriothesley-Best-Builds", "Wriothesley");
        characterIDs.put("Neuvillette-Best-Builds", "Neuvillette");
        characterIDs.put("Furina-Best-Builds", "Furina");
        characterIDs.put("Furina-Best-Builds", "Furina");
        characterIDs.put("412428", "Charlotte");
        return characterIDs;
    }
}
