package com.example.colculationart;


import java.util.HashMap;

public class  UiMap {
    public static HashMap GetUiMap(){
        HashMap<Integer, String> UiBelongCharacterName = new HashMap<>();
        UiBelongCharacterName.put(1, "1_Alhaitham");
        UiBelongCharacterName.put(2, "2_Albedo");
        UiBelongCharacterName.put(3,"3_KamisatoAyaka");
        UiBelongCharacterName.put(4,"4_KamisatoAyato");
        UiBelongCharacterName.put(5,"5_Venti");
        UiBelongCharacterName.put(6,"6_Ganyu");
        UiBelongCharacterName.put(7,"7_Jean");
        UiBelongCharacterName.put(8,"8_Diluc");
        UiBelongCharacterName.put(9, "9_Dehya");
        UiBelongCharacterName.put(10,"10_Yelan");
        UiBelongCharacterName.put(11,"11_Yoimiya");
        UiBelongCharacterName.put(12,"12_AratakiItto");
        UiBelongCharacterName.put(13,"13_KaedeharaKazuha");
        UiBelongCharacterName.put(14,"14_Klee");
        UiBelongCharacterName.put(15,"15_SangonomiyaKokomi");
        UiBelongCharacterName.put(16,"16_Keqing");
        UiBelongCharacterName.put(17,"17_Traveler");
        UiBelongCharacterName.put(18,"17_Traveler");
        UiBelongCharacterName.put(19,"17_Traveler");
        UiBelongCharacterName.put(20,"17_Traveler");
        UiBelongCharacterName.put(21,"21_Mona");
        UiBelongCharacterName.put(22,"22_Nahida");
        UiBelongCharacterName.put(23,"23_Nilou");
        UiBelongCharacterName.put(24,"24_RaidenShogun");
        UiBelongCharacterName.put(25,"25_Cyno");
        UiBelongCharacterName.put(26,"26_Wanderer");
        UiBelongCharacterName.put(27,"27_Xiao");
        UiBelongCharacterName.put(28,"28_Tartaglia");
        UiBelongCharacterName.put(29,"29_Tighnari");
        UiBelongCharacterName.put(30,"30_HuTao");
        UiBelongCharacterName.put(31,"31_Qiqi");
        UiBelongCharacterName.put(32,"32_Zhongli");
        UiBelongCharacterName.put(33,"33_Shenhe");
        UiBelongCharacterName.put(34,"34_Aloy");
        UiBelongCharacterName.put(35,"35_Eula");
        UiBelongCharacterName.put(36,"36_YaeMiko");
        UiBelongCharacterName.put(37,"37_Barbara");
        UiBelongCharacterName.put(38,"38_Bennett");
        UiBelongCharacterName.put(39,"39_Beidou");
        UiBelongCharacterName.put(40,"40_Gorou");
        UiBelongCharacterName.put(41,"41_Diona");
        UiBelongCharacterName.put(42,"42_Dori");
        UiBelongCharacterName.put(43,"43_Candace");
        UiBelongCharacterName.put(44,"44_Collei");
        UiBelongCharacterName.put(45,"45_Kaeya");
        UiBelongCharacterName.put(46,"46_Layla");
        UiBelongCharacterName.put(47,"47_Lisa");
        UiBelongCharacterName.put(48,"48_Mika");
        UiBelongCharacterName.put(49,"49_Ningguang");
        UiBelongCharacterName.put(50,"50_Noelle");
        UiBelongCharacterName.put(51,"51_Rosaria");
        UiBelongCharacterName.put(52,"52_Razor");
        UiBelongCharacterName.put(53,"53_KujouSara");
        UiBelongCharacterName.put(54,"54_Sucrose");
        UiBelongCharacterName.put(55,"55_Sayu");
        UiBelongCharacterName.put(56,"56_Xingqiu");
        UiBelongCharacterName.put(57,"57_KukiShinobu");
        UiBelongCharacterName.put(58,"58_Xinyan");
        UiBelongCharacterName.put(59,"59_Xiangling");
        UiBelongCharacterName.put(60,"60_Thoma");
        UiBelongCharacterName.put(61,"61_Faruzan");
        UiBelongCharacterName.put(62,"62_Fischl");
        UiBelongCharacterName.put(63,"63_ShikanoinHeizou");
        UiBelongCharacterName.put(64,"64_Chongyun");
        UiBelongCharacterName.put(65,"65_Amber");
        UiBelongCharacterName.put(66,"66_YunJin");
        UiBelongCharacterName.put(67,"67_Yanfei");
        UiBelongCharacterName.put(68,"68_Yaoyao");
    return UiBelongCharacterName;
    }
    public static HashMap GetArtNameMap(){
        HashMap<Integer, String> UiBelongArtName = new HashMap<>();
        UiBelongArtName.put(201, "201_adventurer");
        UiBelongArtName.put(202, "202_archaic_petra");
        UiBelongArtName.put(203,"203_berserker");
        UiBelongArtName.put(204,"204_blizzard_strayer");
        UiBelongArtName.put(205,"205_bloodstained_chivalry");
        UiBelongArtName.put(206,"206_brave_heart");
        UiBelongArtName.put(207,"207_crimson_witch_of_flames");
        UiBelongArtName.put(208,"208_deepwood_memories");
        UiBelongArtName.put(209, "209_defenders_will");
        UiBelongArtName.put(210,"210_echoes_of_an_offering");
        UiBelongArtName.put(211,"211_desert_pavilion_chronicle");
        UiBelongArtName.put(212,"212_emblem_of_severed_fate");
        UiBelongArtName.put(213,"213_flower_of_paradise_lost");
        UiBelongArtName.put(214,"214_gilded_dreams");
        UiBelongArtName.put(215,"215_gambler");
        UiBelongArtName.put(216,"216_gladiators_finale");
        UiBelongArtName.put(217,"217_thundering_fury");
        UiBelongArtName.put(218,"218_heart_of_depth");
        UiBelongArtName.put(219,"219_husk_of_opulent_dreams");
        UiBelongArtName.put(220,"220_lavawalker");
        UiBelongArtName.put(221,"221_wanderers_troupe");
        UiBelongArtName.put(222,"222_tenacity_of_the_millelith");
        UiBelongArtName.put(223,"223_instructor");
        UiBelongArtName.put(224,"224_lucky_dog");
        UiBelongArtName.put(225,"225_maiden_beloved");
        UiBelongArtName.put(226,"226_martial_artist");
        UiBelongArtName.put(227,"227_noblesse_oblige");
        UiBelongArtName.put(228,"228_oceanhued_clam");
        UiBelongArtName.put(229,"229_pale_flame");
        UiBelongArtName.put(230,"230_thundersoother");
        UiBelongArtName.put(231,"231_viridescent_venerer");
        UiBelongArtName.put(232,"232_tiny_miracle");
        UiBelongArtName.put(233,"233_vermillion_hereafter");
        UiBelongArtName.put(234,"234_retracing_bolide");
        UiBelongArtName.put(235,"235_shimenawas_reminiscence");
        UiBelongArtName.put(236,"236_the_exile");
        UiBelongArtName.put(237,"237_resolution_of_sojourner");
        UiBelongArtName.put(447,"POKAHZ");
        UiBelongArtName.put(881 ,"POKAHZ");
        UiBelongArtName.put(429 ,"POKAHZ");
        UiBelongArtName.put(451 ,"POKAHZ");
        UiBelongArtName.put(425 ,"POKAHZ");
        UiBelongArtName.put(433 ,"POKAHZ");
        UiBelongArtName.put(434 ,"POKAHZ");
        UiBelongArtName.put(420 ,"POKAHZ");
        return UiBelongArtName;
    }
    public static HashMap GetArtStatMap(){
        HashMap<Integer, String> ArtStatName = new HashMap<>();
        ArtStatName.put(1, "HP");
        ArtStatName.put(2, "HP%");
        ArtStatName.put(3,"АТК");
        ArtStatName.put(4,"АТК%");
        ArtStatName.put(5,"ДЕФ");
        ArtStatName.put(6,"ДЕФ%");
        ArtStatName.put(7,"МС");
        ArtStatName.put(8,"ВЭ%");
        ArtStatName.put(9, "КШ%");
        ArtStatName.put(10,"КУ%");
        ArtStatName.put(11,"Бонус ФИЗ");
        ArtStatName.put(12,"Бонус Анемо");
        ArtStatName.put(13,"Бонус Гидро");
        ArtStatName.put(14,"Бонус Гео");
        ArtStatName.put(15,"Бонус Дендро");
        ArtStatName.put(16,"Бонус Киро");
        ArtStatName.put(17,"Бонус Пиро");
        ArtStatName.put(18,"Бонус Электро");
        ArtStatName.put(19,"Healing Bonus");
        ArtStatName.put(20,"КШ% + КУ%");
        ArtStatName.put(21,"АТК% или МС");
        ArtStatName.put(22,"МС или КУ% и КШ%");
        ArtStatName.put(23,"Healing Bonus или HP%");
        ArtStatName.put(24,"АТК% или ВЭ");
        ArtStatName.put(25,"МС или ВЭ");
        ArtStatName.put(26,"HP% или ВЭ");
        ArtStatName.put(27,"Healing Bonus или АТК%");
        ArtStatName.put(28,"ДЕФ% или ВЭ");
        ArtStatName.put(29,"Бонус ФИЗ или АТК%");
        ArtStatName.put(31,"МС или Бонус Анемо");
        ArtStatName.put(32,"МС или Бонус Анемо");
        ArtStatName.put(33,"АТК или Бонус Электро");
        ArtStatName.put(34,"HP% или Бонус Киро");
        ArtStatName.put(35,"Healing Bonus или ДЕФ%");
        ArtStatName.put(36,"МС или КШ%");
        ArtStatName.put(41 ,"ВЭ или АТК% или МС");
        ArtStatName.put(42 ,"HP% или КУ% или КШ%");
        ArtStatName.put(43 ,"АТК% или ДЕФ%");
        ArtStatName.put(44 ,"КШ% или Healing Bonus");
        return ArtStatName;
    }
}
